name: portable-release-actions-workflow
on:
  workflow_dispatch:

permissions:
    contents: write    
    
jobs:
  build-windows:
    name: Create Windows Release
    runs-on: windows-latest
    env:
      targetZip: qemu-w64-latest.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          python fetch_windows.py
          
      - name: innoextract 
        shell: cmd
        run: |
          qemu.exe /S /D=%CD%\installation &&^
          cd installation &&^
          del qemu-uninstall.exe
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "installation/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
  build-linux:
    name: Create Linux Release
    runs-on: ubuntu-latest
    env:
      targetZip: qemu-linux-installation.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        run: |
          python fetch_linux.py
          
      - name: innoextract 
        run: |
          tar xvJf qemu.tar.xz
          cd qemu-*
          ./configure \
            --target-list=x86_64-softmmu \
            --enable-kvm \
            --enable-system \
            --disable-user \
            --disable-linux-user \
            --disable-bsd-user \
            --disable-guest-agent \
            --disable-gtk \
            --disable-sdl \
            --disable-vnc \
            --disable-spice \
            --disable-curl \
            --disable-docs \
            --disable-tools \
            --enable-virtfs \
            --enable-coroutine-pool \
            --enable-slirp
          make
          mkdir ./installation
          make install DESTDIR=./installation
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "installation"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          name: "Linux Release"
          artifacts: "installation/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
